title: Hello, world! I'm Shreyas Nikte
description: > # this means to ignore newlines until "baseurl:"
  I am an Engineer by training, passion and by birth. If something is broken I will fix it. If it is 
  not broken, I will break it (and then fix it). I dont really think it is something thaat I can control. 
  That could be the reason why this website exists. If you can see this, nice, it is fixed! If you 
  cannot read this, I might have broken something while trying to fix something. In either case, thanks for dropping by!
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "nikte.work" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Shreyas Nikte # add your name
author-img: david-freeman11.jpg # add your photo
about-author: I am an Engineer by training, passion and by birth. If something is broken I will fix it. If it is 
  not broken, I will break it (and then fix it). I dont really think it is something thaat I can control. 
  That could be the reason why this website exists. If you can see this, nice, it is fixed! If you 
  cannot read this, I might have broken something while trying to fix something. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: shreyasnikte # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown11 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
